steps:
  # Build shared package
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'shared', '--target', 'shared-builder', '.']
  
  # Build and push API
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/api:$SHORT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/api:latest',
      '--target', 'api',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/api:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/api:latest']
  
  # Build and push Workers
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/workers:$SHORT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/workers:latest',
      '--target', 'workers',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/workers:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/workers:latest']
  
  # Build and push Web
  - name: 'gcr.io/cloud-builders/docker'
    args: [
      'build',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/web:$SHORT_SHA',
      '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/web:latest',
      '--target', 'web',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_URL=${_NEXT_PUBLIC_SUPABASE_URL}',
      '--build-arg', 'NEXT_PUBLIC_SUPABASE_ANON_KEY=${_NEXT_PUBLIC_SUPABASE_ANON_KEY}',
      '--build-arg', 'NEXT_PUBLIC_API_URL=${_NEXT_PUBLIC_API_URL}',
      '.'
    ]
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/web:$SHORT_SHA']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/web:latest']
  
  # Deploy API to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'glowguide-api',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/api:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
  
  # Deploy Workers to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'glowguide-workers',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/workers:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--no-allow-unauthenticated'
    ]
  
  # Deploy Web to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args: [
      'run', 'deploy', 'glowguide-web',
      '--image', 'us-central1-docker.pkg.dev/$PROJECT_ID/glowguide/web:$SHORT_SHA',
      '--region', 'us-central1',
      '--platform', 'managed',
      '--allow-unauthenticated'
    ]
  
  # Run database migrations
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        # Install PostgreSQL client
        apt-get update && apt-get install -y postgresql-client
        
        # Download Cloud SQL Proxy
        wget https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O cloud_sql_proxy
        chmod +x cloud_sql_proxy
        
        # Start Cloud SQL Proxy in background
        ./cloud_sql_proxy -instances=${_CLOUD_SQL_CONNECTION}=tcp:5432 &
        
        # Wait for proxy to be ready
        sleep 5
        
        # Run migrations
        for file in supabase/migrations/*.sql; do
          PGPASSWORD=${_DB_PASSWORD} psql -h 127.0.0.1 -U ${_DB_USER} -d ${_DB_NAME} -f $$file
        done
        
        # Stop proxy
        pkill cloud_sql_proxy

timeout: 1800s
options:
  machineType: 'N1_HIGHCPU_8'
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _NEXT_PUBLIC_SUPABASE_URL: 'https://your-project.supabase.co'
  _NEXT_PUBLIC_SUPABASE_ANON_KEY: 'your-anon-key'
  _NEXT_PUBLIC_API_URL: 'https://glowguide-api-xxxxx-uc.a.run.app'
  _CLOUD_SQL_CONNECTION: 'project:region:instance'
  _DB_USER: 'glowguide'
  _DB_PASSWORD: 'your-password'
  _DB_NAME: 'glowguide'
